# Generated by Django 5.1.4 on 2025-01-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dishes', models.IntegerField()),
                ('image', models.ImageField(upload_to='category')),
            ],
        ),
    ]
